# Generated by Django 4.2.5 on 2023-09-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_is_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_offered',
        ),
    ]
